In [1]:
import requests
import pandas as pd
import matplotlib.pyplot as plt
import pyarrow

In [2]:
weekly_hvac_permits = pd.read_parquet("../data/weekly_hvac_permits.parquet")

In [3]:
weekly_hvac_permits.index.dtype

dtype('int64')

In [4]:
weekly_hvac_permits

            ds    y unique_id
0   2010-01-10  265   la_hvac
1   2010-01-17  261   la_hvac
2   2010-01-24  196   la_hvac
3   2010-01-31  253   la_hvac
4   2010-02-07  259   la_hvac
..         ...  ...       ...
867 2026-08-23  385   la_hvac
868 2026-08-30  372   la_hvac
869 2026-09-06  358   la_hvac
870 2026-09-13  299   la_hvac
871 2026-09-20  346   la_hvac

[872 rows x 3 columns]

In [13]:
mask = weekly_hvac_permits['ds'] < '2026-03-22'
print(mask)

0       True
1       True
2       True
3       True
4       True
       ...
867    False
868    False
869    False
870    False
871    False
Name: ds, Length: 872, dtype: bool

In [15]:
weekly_hvac_permits.loc[mask]

            ds    y unique_id
0   2010-01-10  265   la_hvac
1   2010-01-17  261   la_hvac
2   2010-01-24  196   la_hvac
3   2010-01-31  253   la_hvac
4   2010-02-07  259   la_hvac
..         ...  ...       ...
840 2026-02-15  281   la_hvac
841 2026-02-22  281   la_hvac
842 2026-03-01  302   la_hvac
843 2026-03-08  282   la_hvac
844 2026-03-15  270   la_hvac

[845 rows x 3 columns]

In [18]:
used_set = weekly_hvac_permits.iloc[:-26]

In [19]:
used_set

            ds    y unique_id
0   2010-01-10  265   la_hvac
1   2010-01-17  261   la_hvac
2   2010-01-24  196   la_hvac
3   2010-01-31  253   la_hvac
4   2010-02-07  259   la_hvac
..         ...  ...       ...
841 2026-02-22  281   la_hvac
842 2026-03-01  302   la_hvac
843 2026-03-08  282   la_hvac
844 2026-03-15  270   la_hvac
845 2026-03-22  336   la_hvac

[846 rows x 3 columns]

In [31]:
origins = used_set['ds'].iloc[793:838:4]
print(origins)

793   2025-03-23
797   2025-04-20
801   2025-05-18
805   2025-06-15
809   2025-07-13
813   2025-08-10
817   2025-09-07
821   2025-10-05
825   2025-11-02
829   2025-11-30
833   2025-12-28
837   2026-01-25
Name: ds, dtype: datetime64[us]

In [ ]:
for origin in origins:
  origin_slice = used_set['ds'] < origin
  print(origin_slice)

0       True
1       True
2       True
3       True
4       True
       ...
841    False
842    False
843    False
844    False
845    False
Name: ds, Length: 846, dtype: bool
0       True
1       True
2       True
3       True
4       True
       ...
841    False
842    False
843    False
844    False
845    False
Name: ds, Length: 846, dtype: bool
0       True
1       True
2       True
3       True
4       True
       ...
841    False
842    False
843    False
844    False
845    False
Name: ds, Length: 846, dtype: bool
0       True
1       True
2       True
3       True
4       True
       ...
841    False
842    False
843    False
844    False
845    False
Name: ds, Length: 846, dtype: bool
0       True
1       True
2       True
3       True
4       True
       ...
841    False
842    False
843    False
844    False
845    False
Name: ds, Length: 846, dtype: bool
0       True
1       True
2       True
3       True
4       True
       ...
841    False
842    False
843    False
844    False
845    False
Name: ds, Length: 846, dtype: bool
0       True
1       True
2       True
3       True
4       True
       ...
841    False
842    False
843    False
844    False
845    False
Name: ds, Length: 846, dtype: bool
0       True
1       True
2       True
3       True
4       True
       ...
841    False
842    False
843    False
844    False
845    False
Name: ds, Length: 846, dtype: bool
0       True
1       True
2       True
3       True
4       True
       ...
841    False
842    False
843    False
844    False
845    False
Name: ds, Length: 846, dtype: bool
0       True
1       True
2       True
3       True
4       True
       ...
841    False
842    False
843    False
844    False
845    False
Name: ds, Length: 846, dtype: bool
0       True
1       True
2       True
3       True
4       True
       ...
841    False
842    False
843    False
844    False
845    False
Name: ds, Length: 846, dtype: bool
0       True
1       True
2       True
3       True
4       True
       ...
841    False
842    False
843    False
844    False
845    False
Name: ds, Length: 846, dtype: bool