In [9]:
import requests
import pandas as pd
import matplotlib.pyplot as plt
import pyarrow

url = 'https://archive-api.open-meteo.com/v1/archive?latitude=34.07883,33.95302,34.174899&longitude=-118.2637,-118.40028,-118.615271&start_date=2010-01-03&end_date=2026-10-07&daily=temperature_2m_min,temperature_2m_max&models=era5_land&timezone=America%2FLos_Angeles&temperature_unit=fahrenheit'

resp = requests.get(url)
data = resp.json()

In [10]:
type(data), len(data)

(list, 3)

In [ ]:
type(data[0])

dict

In [13]:
data[0]

{'latitude': 34.1,
 'longitude': -118.3,
 'generationtime_ms': 148.57912063598633,
 'utc_offset_seconds': -25200,
 'timezone': 'America/Los_Angeles',
 'timezone_abbreviation': 'GMT-7',
 'elevation': 149.0,
 'daily_units': {'time': 'iso8601',
  'temperature_2m_min': '°F',
  'temperature_2m_max': '°F'},
 'daily': {'time': ['2010-01-03',
   '2010-01-04',
   '2010-01-05',
   '2010-01-06',
   '2010-01-07',
   '2010-01-08',
   '2010-01-09',
   '2010-01-10',
   '2010-01-11',
   '2010-01-12',
   '2010-01-13',
   '2010-01-14',
   '2010-01-15',
   '2010-01-16',
   '2010-01-17',
   '2010-01-18',
   '2010-01-19',
   '2010-01-20',
   '2010-01-21',
   '2010-01-22',
   '2010-01-23',
   '2010-01-24',
   '2010-01-25',
   '2010-01-26',
   '2010-01-27',
   '2010-01-28',
   '2010-01-29',
   '2010-01-30',
   '2010-01-31',
   '2010-02-01',
   '2010-02-02',
   '2010-02-03',
   '2010-02-04',
   '2010-02-05',
   '2010-02-06',
   '2010-02-07',
   '2010-02-08',
   '2010-02-09',
   '2010-02-10',
   '2010-02-11',
   '2010-02-12',
   '2010-02-13',
   '2010-02-14',
   '2010-02-15',
   '2010-02-16',
   '2010-02-17',
   '2010-02-18',
   '2010-02-19',
   '2010-02-20',
   '2010-02-21',
   '2010-02-22',
   '2010-02-23',
   '2010-02-24',
   '2010-02-25',
   '2010-02-26',
   '2010-02-27',
   '2010-02-28',
   '2010-03-01',
   '2010-03-02',
   '2010-03-03',
   '2010-03-04',
   '2010-03-05',
   '2010-03-06',
   '2010-03-07',
   '2010-03-08',
   '2010-03-09',
   '2010-03-10',
   '2010-03-11',
   '2010-03-12',
   '2010-03-13',
   '2010-03-14',
   '2010-03-15',
   '2010-03-16',
   '2010-03-17',
   '2010-03-18',
   '2010-03-19',
   '2010-03-20',
   '2010-03-21',
   '2010-03-22',
   '2010-03-23',
   '2010-03-24',
   '2010-03-25',
   '2010-03-26',
   '2010-03-27',
   '2010-03-28',
   '2010-03-29',
   '2010-03-30',
   '2010-03-31',
   '2010-04-01',
   '2010-04-02',
   '2010-04-03',
   '2010-04-04',
   '2010-04-05',
   '2010-04-06',
   '2010-04-07',
   '2010-04-08',
   '2010-04-09',
   '2010-04-10',
   '2010-04-11',
   '2010-04-12',
   '2010-04-13',
   '2010-04-14',
   '2010-04-15',
   '2010-04-16',
   '2010-04-17',
   '2010-04-18',
   '2010-04-19',
   '2010-04-20',
   '2010-04-21',
   '2010-04-22',
   '2010-04-23',
   '2010-04-24',
   '2010-04-25',
   '2010-04-26',
   '2010-04-27',
   '2010-04-28',
   '2010-04-29',
   '2010-04-30',
   '2010-05-01',
   '2010-05-02',
   '2010-05-03',
   '2010-05-04',
   '2010-05-05',
   '2010-05-06',
   '2010-05-07',
   '2010-05-08',
   '2010-05-09',
   '2010-05-10',
   '2010-05-11',
   '2010-05-12',
   '2010-05-13',
   '2010-05-14',
   '2010-05-15',
   '2010-05-16',
   '2010-05-17',
   '2010-05-18',
   '2010-05-19',
   '2010-05-20',
   '2010-05-21',
   '2010-05-22',
   '2010-05-23',
   '2010-05-24',
   '2010-05-25',
   '2010-05-26',
   '2010-05-27',
   '2010-05-28',
   '2010-05-29',
   '2010-05-30',
   '2010-05-31',
   '2010-06-01',
   '2010-06-02',
   '2010-06-03',
   '2010-06-04',
   '2010-06-05',
   '2010-06-06',
   '2010-06-07',
   '2010-06-08',
   '2010-06-09',
   '2010-06-10',
   '2010-06-11',
   '2010-06-12',
   '2010-06-13',
   '2010-06-14',
   '2010-06-15',
   '2010-06-16',
   '2010-06-17',
   '2010-06-18',
   '2010-06-19',
   '2010-06-20',
   '2010-06-21',
   '2010-06-22',
   '2010-06-23',
   '2010-06-24',
   '2010-06-25',
   '2010-06-26',
   '2010-06-27',
   '2010-06-28',
   '2010-06-29',
   '2010-06-30',
   '2010-07-01',
   '2010-07-02',
   '2010-07-03',
   '2010-07-04',
   '2010-07-05',
   '2010-07-06',
   '2010-07-07',
   '2010-07-08',
   '2010-07-09',
   '2010-07-10',
   '2010-07-11',
   '2010-07-12',
   '2010-07-13',
   '2010-07-14',
   '2010-07-15',
   '2010-07-16',
   '2010-07-17',
   '2010-07-18',
   '2010-07-19',
   '2010-07-20',
   '2010-07-21',
   '2010-07-22',
   '2010-07-23',
   '2010-07-24',
   '2010-07-25',
   '2010-07-26',
   '2010-07-27',
   '2010-07-28',
   '2010-07-29',
   '2010-07-30',
   '2010-07-31',
   '2010-08-01',
   '2010-08-02',
   '2010-08-03',
   '2010-08-04',
   '2010-08-05',
   '2010-08-06',
   '2010-08-07',
   '2010-08-08',
   '2010-08-09',
   '2010-08-10',
   '2010-08-11',
   '2010-08-12',
   '2010-08-13',
   '2010-08-14',
   '2010-08-15',
   '2010-08-16',
   '2010-08-17',
   '2010-08-18',
   '2010-08-19',
   '2010-08-20',
   '2010-08-21',
   '2010-08-22',
   '2010-08-23',
   '2010-08-24',
   '2010-08-25',
   '2010-08-26',
   '2010-08-27',
   '2010-08-28',
   '2010-08-29',
   '2010-08-30',
   '2010-08-31',
   '2010-09-01',
   '2010-09-02',
   '2010-09-03',
   '2010-09-04',
   '2010-09-05',
   '2010-09-06',
   '2010-09-07',
   '2010-09-08',
   '2010-09-09',
   '2010-09-10',
   '2010-09-11',
   '2010-09-12',
   '2010-09-13',
   '2010-09-14',
   '2010-09-15',
   '2010-09-16',
   '2010-09-17',
   '2010-09-18',
   '2010-09-19',
   '2010-09-20',
   '2010-09-21',
   '2010-09-22',
   '2010-09-23',
   '2010-09-24',
   '2010-09-25',
   '2010-09-26',
   '2010-09-27',
   '2010-09-28',
   '2010-09-29',
   '2010-09-30',
   '2010-10-01',
   '2010-10-02',
   '2010-10-03',
   '2010-10-04',
   '2010-10-05',
   '2010-10-06',
   '2010-10-07',
   '2010-10-08',
   '2010-10-09',
   '2010-10-10',
   '2010-10-11',
   '2010-10-12',
   '2010-10-13',
   '2010-10-14',
   '2010-10-15',
   '2010-10-16',
   '2010-10-17',
   '2010-10-18',
   '2010-10-19',
   '2010-10-20',
   '2010-10-21',
   '2010-10-22',
   '2010-10-23',
   '2010-10-24',
   '2010-10-25',
   '2010-10-26',
   '2010-10-27',
   '2010-10-28',
   '2010-10-29',
   '2010-10-30',
   '2010-10-31',
   '2010-11-01',
   '2010-11-02',
   '2010-11-03',
   '2010-11-04',
   '2010-11-05',
   '2010-11-06',
   '2010-11-07',
   '2010-11-08',
   '2010-11-09',
   '2010-11-10',
   '2010-11-11',
   '2010-11-12',
   '2010-11-13',
   '2010-11-14',
   '2010-11-15',
   '2010-11-16',
   '2010-11-17',
   '2010-11-18',
   '2010-11-19',
   '2010-11-20',
   '2010-11-21',
   '2010-11-22',
   '2010-11-23',
   '2010-11-24',
   '2010-11-25',
   '2010-11-26',
   '2010-11-27',
   '2010-11-28',
   '2010-11-29',
   '2010-11-30',
   '2010-12-01',
   '2010-12-02',
   '2010-12-03',
   '2010-12-04',
   '2010-12-05',
   '2010-12-06',
   '2010-12-07',
   '2010-12-08',
   '2010-12-09',
   '2010-12-10',
   '2010-12-11',
   '2010-12-12',
   '2010-12-13',
   '2010-12-14',
   '2010-12-15',
   '2010-12-16',
   '2010-12-17',
   '2010-12-18',
   '2010-12-19',
   '2010-12-20',
   '2010-12-21',
   '2010-12-22',
   '2010-12-23',
   '2010-12-24',
   '2010-12-25',
   '2010-12-26',
   '2010-12-27',
   '2010-12-28',
   '2010-12-29',
   '2010-12-30',
   '2010-12-31',
   '2011-01-01',
   '2011-01-02',
   '2011-01-03',
   '2011-01-04',
   '2011-01-05',
   '2011-01-06',
   '2011-01-07',
   '2011-01-08',
   '2011-01-09',
   '2011-01-10',
   '2011-01-11',
   '2011-01-12',
   '2011-01-13',
   '2011-01-14',
   '2011-01-15',
   '2011-01-16',
   '2011-01-17',
   '2011-01-18',
   '2011-01-19',
   '2011-01-20',
   '2011-01-21',
   '2011-01-22',
   '2011-01-23',
   '2011-01-24',
   '2011-01-25',
   '2011-01-26',
   '2011-01-27',
   '2011-01-28',
   '2011-01-29',
   '2011-01-30',
   '2011-01-31',
   '2011-02-01',
   '2011-02-02',
   '2011-02-03',
   '2011-02-04',
   '2011-02-05',
   '2011-02-06',
   '2011-02-07',
   '2011-02-08',
   '2011-02-09',
   '2011-02-10',
   '2011-02-11',
   '2011-02-12',
   '2011-02-13',
   '2011-02-14',
   '2011-02-15',
   '2011-02-16',
   '2011-02-17',
   '2011-02-18',
   '2011-02-19',
   '2011-02-20',
   '2011-02-21',
   '2011-02-22',
   '2011-02-23',
   '2011-02-24',
   '2011-02-25',
   '2011-02-26',
   '2011-02-27',
   '2011-02-28',
   '2011-03-01',
   '2011-03-02',
   '2011-03-03',
   '2011-03-04',
   '2011-03-05',
   '2011-03-06',
   '2011-03-07',
   '2011-03-08',
   '2011-03-09',
   '2011-03-10',
   '2011-03-11',
   '2011-03-12',
   '2011-03-13',
   '2011-03-14',
   '2011-03-15',
   '2011-03-16',
   '2011-03-17',
   '2011-03-18',
   '2011-03-19',
   '2011-03-20',
   '2011-03-21',
   '2011-03-22',
   '2011-03-23',
   '2011-03-24',
   '2011-03-25',
   '2011-03-26',
   '2011-03-27',
   '2011-03-28',
   '2011-03-29',
   '2011-03-30',
   '2011-03-31',
   '2011-04-01',
   '2011-04-02',
   '2011-04-03',
   '2011-04-04',
   '2011-04-05',
   '2011-04-06',
   '2011-04-07',
   '2011-04-08',
   '2011-04-09',
   '2011-04-10',
   '2011-04-11',
   '2011-04-12',
   '2011-04-13',
   '2011-04-14',
   '2011-04-15',
   '2011-04-16',
   '2011-04-17',
   '2011-04-18',
   '2011-04-19',
   '2011-04-20',
   '2011-04-21',
   '2011-04-22',
   '2011-04-23',
   '2011-04-24',
   '2011-04-25',
   '2011-04-26',
   '2011-04-27',
   '2011-04-28',
   '2011-04-29',
   '2011-04-30',
   '2011-05-01',
   '2011-05-02',
   '2011-05-03',
   '2011-05-04',
   '2011-05-05',
   '2011-05-06',
   '2011-05-07',
   '2011-05-08',
   '2011-05-09',
   '2011-05-10',
   '2011-05-11',
   '2011-05-12',
   '2011-05-13',
   '2011-05-14',
   '2011-05-15',
   '2011-05-16',
   '2011-05-17',
   '2011-05-18',
   '2011-05-19',
   '2011-05-20',
   '2011-05-21',
   '2011-05-22',
   '2011-05-23',
   '2011-05-24',
   '2011-05-25',
   '2011-05-26',
   '2011-05-27',
   '2011-05-28',
   '2011-05-29',
   '2011-05-30',
   '2011-05-31',
   '2011-06-01',
   '2011-06-02',
   '2011-06-03',
   '2011-06-04',
   '2011-06-05',
   '2011-06-06',
   '2011-06-07',
   '2011-06-08',
   '2011-06-09',
   '2011-06-10',
   '2011-06-11',
   '2011-06-12',
   '2011-06-13',
   '2011-06-14',
   '2011-06-15',
   '2011-06-16',
   '2011-06-17',
   '2011-06-18',
   '2011-06-19',
   '2011-06-20',
   '2011-06-21',
   '2011-06-22',
   '2011-06-23',
   '2011-06-24',
   '2011-06-25',
   '2011-06-26',
   '2011-06-27',
   '2011-06-28',
   '2011-06-29',
   '2011-06-30',
   '2011-07-01',
   '2011-07-02',
   '2011-07-03',
   '2011-07-04',
   '2011-07-05',
   '2011-07-06',
   '2011-07-07',
   '2011-07-08',
   '2011-07-09',
   '2011-07-10',
   '2011-07-11',
   '2011-07-12',
   '2011-07-13',
   '2011-07-14',
   '2011-07-15',
   '2011-07-16',
   '2011-07-17',
   '2011-07-18',
   '2011-07-19',
   '2011-07-20',
   '2011-07-21',
   '2011-07-22',
   '2011-07-23',
   '2011-07-24',
   '2011-07-25',
   '2011-07-26',
   '2011-07-27',
   '2011-07-28',
   '2011-07-29',
   '2011-07-30',
   '2011-07-31',
   '2011-08-01',
   '2011-08-02',
   '2011-08-03',
   '2011-08-04',
   '2011-08-05',
   '2011-08-06',
   '2011-08-07',
   '2011-08-08',
   '2011-08-09',
   '2011-08-10',
   '2011-08-11',
   '2011-08-12',
   '2011-08-13',
   '2011-08-14',
   '2011-08-15',
   '2011-08-16',
   '2011-08-17',
   '2011-08-18',
   '2011-08-19',
   '2011-08-20',
   '2011-08-21',
   '2011-08-22',
   '2011-08-23',
   '2011-08-24',
   '2011-08-25',
   '2011-08-26',
   '2011-08-27',
   '2011-08-28',
   '2011-08-29',
   '2011-08-30',
   '2011-08-31',
   '2011-09-01',
   '2011-09-02',
   '2011-09-03',
   '2011-09-04',
   '2011-09-05',
   '2011-09-06',
   '2011-09-07',
   '2011-09-08',
   '2011-09-09',
   '2011-09-10',
   '2011-09-11',
   '2011-09-12',
   '2011-09-13',
   '2011-09-14',
   '2011-09-15',
   '2011-09-16',
   '2011-09-17',
   '2011-09-18',
   '2011-09-19',
   '2011-09-20',
   '2011-09-21',
   '2011-09-22',
   '2011-09-23',
   '2011-09-24',
   '2011-09-25',
   '2011-09-26',
   '2011-09-27',
   '2011-09-28',
   '2011-09-29',
   '2011-09-30',
   '2011-10-01',
   '2011-10-02',
   '2011-10-03',
   '2011-10-04',
   '2011-10-05',
   '2011-10-06',
   '2011-10-07',
   '2011-10-08',
   '2011-10-09',
   '2011-10-10',
   '2011-10-11',
   '2011-10-12',
   '2011-10-13',
   '2011-10-14',
   '2011-10-15',
   '2011-10-16',
   '2011-10-17',
   '2011-10-18',
   '2011-10-19',
   '2011-10-20',
   '2011-10-21',
   '2011-10-22',
   '2011-10-23',
   '2011-10-24',
   '2011-10-25',
   '2011-10-26',
   '2011-10-27',
   '2011-10-28',
   '2011-10-29',
   '2011-10-30',
   '2011-10-31',
   '2011-11-01',
   '2011-11-02',
   '2011-11-03',
   '2011-11-04',
   '2011-11-05',
   '2011-11-06',
   '2011-11-07',
   '2011-11-08',
   '2011-11-09',
   '2011-11-10',
   '2011-11-11',
   '2011-11-12',
   '2011-11-13',
   '2011-11-14',
   '2011-11-15',
   '2011-11-16',
   '2011-11-17',
   '2011-11-18',
   '2011-11-19',
   '2011-11-20',
   '2011-11-21',
   '2011-11-22',
   '2011-11-23',
   '2011-11-24',
   '2011-11-25',
   '2011-11-26',
   '2011-11-27',
   '2011-11-28',
   '2011-11-29',
   '2011-11-30',
   '2011-12-01',
   '2011-12-02',
   '2011-12-03',
   '2011-12-04',
   '2011-12-05',
   '2011-12-06',
   '2011-12-07',
   '2011-12-08',
   '2011-12-09',
   '2011-12-10',
   '2011-12-11',
   '2011-12-12',
   '2011-12-13',
   '2011-12-14',
   '2011-12-15',
   '2011-12-16',
   '2011-12-17',
   '2011-12-18',
   '2011-12-19',
   '2011-12-20',
   '2011-12-21',
   '2011-12-22',
   '2011-12-23',
   '2011-12-24',
   '2011-12-25',
   '2011-12-26',
   '2011-12-27',
   '2011-12-28',
   '2011-12-29',
   '2011-12-30',
   '2011-12-31',
   '2012-01-01',
   '2012-01-02',
   '2012-01-03',
   '2012-01-04',
   '2012-01-05',
   '2012-01-06',
   '2012-01-07',
   '2012-01-08',
   '2012-01-09',
   '2012-01-10',
   '2012-01-11',
   '2012-01-12',
   '2012-01-13',
   '2012-01-14',
   '2012-01-15',
   '2012-01-16',
   '2012-01-17',
   '2012-01-18',
   '2012-01-19',
   '2012-01-20',
   '2012-01-21',
   '2012-01-22',
   '2012-01-23',
   '2012-01-24',
   '2012-01-25',
   '2012-01-26',
   '2012-01-27',
   '2012-01-28',
   '2012-01-29',
   '2012-01-30',
   '2012-01-31',
   '2012-02-01',
   '2012-02-02',
   '2012-02-03',
   '2012-02-04',
   '2012-02-05',
   '2012-02-06',
   '2012-02-07',
   '2012-02-08',
   '2012-02-09',
   '2012-02-10',
   '2012-02-11',
   '2012-02-12',
   '2012-02-13',
   '2012-02-14',
   '2012-02-15',
   '2012-02-16',
   '2012-02-17',
   '2012-02-18',
   '2012-02-19',
   '2012-02-20',
   '2012-02-21',
   '2012-02-22',
   '2012-02-23',
   '2012-02-24',
   '2012-02-25',
   '2012-02-26',
   '2012-02-27',
   '2012-02-28',
   '2012-02-29',
   '2012-03-01',
   '2012-03-02',
   '2012-03-03',
   '2012-03-04',
   '2012-03-05',
   '2012-03-06',
   '2012-03-07',
   '2012-03-08',
   '2012-03-09',
   '2012-03-10',
   '2012-03-11',
   '2012-03-12',
   '2012-03-13',
   '2012-03-14',
   '2012-03-15',
   '2012-03-16',
   '2012-03-17',
   '2012-03-18',
   '2012-03-19',
   '2012-03-20',
   '2012-03-21',
   '2012-03-22',
   '2012-03-23',
   '2012-03-24',
   '2012-03-25',
   '2012-03-26',
   '2012-03-27',
   '2012-03-28',
   '2012-03-29',
   '2012-03-30',
   '2012-03-31',
   '2012-04-01',
   '2012-04-02',
   '2012-04-03',
   '2012-04-04',
   '2012-04-05',
   '2012-04-06',
   '2012-04-07',
   '2012-04-08',
   '2012-04-09',
   '2012-04-10',
   '2012-04-11',
   '2012-04-12',
   '2012-04-13',
   '2012-04-14',
   '2012-04-15',
   '2012-04-16',
   '2012-04-17',
   '2012-04-18',
   '2012-04-19',
   '2012-04-20',
   '2012-04-21',
   '2012-04-22',
   '2012-04-23',
   '2012-04-24',
   '2012-04-25',
   '2012-04-26',
   '2012-04-27',
   '2012-04-28',
   '2012-04-29',
   '2012-04-30',
   '2012-05-01',
   '2012-05-02',
   '2012-05-03',
   '2012-05-04',
   '2012-05-05',
   '2012-05-06',
   '2012-05-07',
   '2012-05-08',
   '2012-05-09',
   '2012-05-10',
   '2012-05-11',
   '2012-05-12',
   '2012-05-13',
   '2012-05-14',
   '2012-05-15',
   '2012-05-16',
   '2012-05-17',
   '2012-05-18',
   '2012-05-19',
   '2012-05-20',
   '2012-05-21',
   '2012-05-22',
   '2012-05-23',
   '2012-05-24',
   '2012-05-25',
   '2012-05-26',
   '2012-05-27',
   '2012-05-28',
   '2012-05-29',
   '2012-05-30',
   '2012-05-31',
   '2012-06-01',
   '2012-06-02',
   '2012-06-03',
   '2012-06-04',
   '2012-06-05',
   '2012-06-06',
   '2012-06-07',
   '2012-06-08',
   '2012-06-09',
   '2012-06-10',
   '2012-06-11',
   '2012-06-12',
   '2012-06-13',
   '2012-06-14',
   '2012-06-15',
   '2012-06-16',
   '2012-06-17',
   '2012-06-18',
   '2012-06-19',
   '2012-06-20',
   '2012-06-21',
   '2012-06-22',
   '2012-06-23',
   '2012-06-24',
   '2012-06-25',
   '2012-06-26',
   '2012-06-27',
   '2012-06-28',
   '2012-06-29',
   '2012-06-30',
   '2012-07-01',
   '2012-07-02',
   '2012-07-03',
   '2012-07-04',
   '2012-07-05',
   '2012-07-06',
   '2012-07-07',
   '2012-07-08',
   '2012-07-09',
   '2012-07-10',
   '2012-07-11',
   '2012-07-12',
   '2012-07-13',
   '2012-07-14',
   '2012-07-15',
   '2012-07-16',
   '2012-07-17',
   '2012-07-18',
   '2012-07-19',
   '2012-07-20',
   '2012-07-21',
   '2012-07-22',
   '2012-07-23',
   '2012-07-24',
   '2012-07-25',
   '2012-07-26',
   '2012-07-27',
   '2012-07-28',
   '2012-07-29',
   '2012-07-30',
   '2012-07-31',
   '2012-08-01',
   '2012-08-02',
   '2012-08-03',
   '2012-08-04',
   '2012-08-05',
   '2012-08-06',
   '2012-08-07',
   '2012-08-08',
   '2012-08-09',
   '2012-08-10',
   '2012-08-11',
   '2012-08-12',
   '2012-08-13',
   '2012-08-14',
   '2012-08-15',
   '2012-08-16',
   '2012-08-17',
   '2012-08-18',
   '2012-08-19',
   '2012-08-20',
   '2012-08-21',
   '2012-08-22',
   '2012-08-23',
   '2012-08-24',
   '2012-08-25',
   '2012-08-26',
   '2012-08-27',
   '2012-08-28',
   '2012-08-29',
   '2012-08-30',
   '2012-08-31',
   '2012-09-01',
   '2012-09-02',
   '2012-09-03',
   '2012-09-04',
   '2012-09-05',
   '2012-09-06',
   '2012-09-07',
   '2012-09-08',
   '2012-09-09',
   '2012-09-10',
   '2012-09-11',
   '2012-09-12',
   '2012-09-13',
   '2012-09-14',
   '2012-09-15',
   '2012-09-16',
   '2012-09-17',
   '2012-09-18',
   '2012-09-19',
   '2012-09-20',
   '2012-09-21',
   '2012-09-22',
   '2012-09-23',
   '2012-09-24',
   '2012-09-25',
   '2012-09-26',
   '2012-09-27',
   '2012-09-28',
   ...],
  'temperature_2m_min': [45.6,
   46.4,
   43.8,
   47.5,
   42.5,
   48.3,
   47.4,
   47.9,
   47.4,
   46.5,
   47.7,
   43.2,
   43.5,
   46.3,
   45.4,
   43.1,
   43.3,
   43.7,
   45.1,
   38.7,
   35.3,
   37.1,
   38.1,
   40.7,
   43.9,
   42.3,
   42.9,
   43.5,
   42.0,
   42.8,
   45.6,
   42.3,
   49.0,
   49.2,
   46.9,
   36.6,
   40.2,
   40.0,
   34.8,
   40.6,
   41.7,
   42.1,
   46.2,
   47.1,
   49.2,
   49.7,
   49.8,
   50.1,
   46.5,
   46.6,
   43.3,
   38.3,
   43.6,
   43.5,
   47.3,
   44.6,
   40.3,
   44.0,
   50.3,
   48.7,
   43.1,
   40.9,
   46.5,
   41.4,
   44.2,
   41.1,
   37.4,
   38.0,
   40.2,
   44.5,
   40.6,
   42.4,
   48.0,
   50.6,
   49.5,
   46.7,
   45.9,
   48.1,
   46.3,
   47.8,
   46.4,
   48.6,
   43.9,
   46.5,
   48.1,
   48.7,
   50.5,
   46.7,
   45.1,
   41.8,
   42.8,
   44.2,
   48.0,
   40.1,
   45.6,
   49.1,
   49.4,
   49.7,
   47.8,
   47.4,
   41.8,
   43.9,
   44.5,
   47.2,
   47.0,
   49.4,
   49.2,
   48.0,
   44.1,
   42.1,
   41.5,
   44.8,
   46.5,
   51.0,
   51.1,
   51.5,
   46.3,
   44.3,
   46.6,
   49.2,
   50.1,
   52.9,
   53.4,
   53.1,
   51.2,
   53.8,
   51.7,
   47.9,
   46.0,
   46.2,
   53.7,
   52.5,
   52.8,
   55.5,
   51.6,
   52.7,
   51.0,
   53.6,
   55.0,
   53.6,
   49.0,
   50.5,
   47.7,
   51.6,
   55.5,
   49.0,
   50.1,
   54.6,
   57.4,
   53.4,
   52.7,
   56.1,
   58.6,
   62.2,
   59.9,
   58.5,
   56.9,
   55.9,
   56.3,
   55.4,
   56.1,
   54.8,
   57.2,
   59.8,
   54.5,
   54.6,
   55.0,
   53.2,
   54.1,
   53.7,
   52.9,
   57.3,
   57.6,
   58.2,
   57.1,
   57.5,
   59.0,
   56.9,
   57.6,
   59.3,
   59.2,
   56.5,
   55.6,
   56.6,
   55.0,
   55.5,
   55.7,
   57.6,
   62.1,
   60.3,
   60.0,
   62.0,
   66.3,
   70.6,
   72.7,
   71.0,
   68.5,
   65.3,
   62.6,
   60.0,
   58.8,
   60.9,
   63.3,
   61.4,
   58.6,
   56.9,
   56.9,
   59.5,
   59.4,
   59.8,
   59.1,
   63.2,
   66.8,
   62.5,
   59.2,
   58.2,
   57.8,
   56.1,
   55.5,
   57.1,
   55.7,
   56.8,
   59.8,
   59.5,
   62.0,
   63.0,
   68.1,
   71.1,
   70.2,
   65.4,
   67.5,
   69.2,
   62.5,
   67.3,
   74.4,
   75.3,
   66.2,
   59.0,
   56.0,
   55.2,
   56.2,
   59.1,
   60.8,
   65.4,
   67.9,
   65.4,
   60.8,
   58.1,
   57.8,
   55.9,
   53.2,
   56.3,
   59.4,
   63.3,
   62.2,
   61.2,
   56.4,
   56.4,
   57.7,
   59.4,
   59.3,
   56.4,
   55.9,
   53.3,
   57.2,
   60.9,
   62.6,
   70.6,
   69.9,
   66.3,
   66.9,
   66.3,
   66.3,
   64.0,
   60.3,
   54.7,
   55.4,
   49.8,
   50.6,
   54.0,
   60.0,
   59.4,
   62.2,
   59.7,
   60.4,
   57.8,
   57.6,
   56.5,
   57.4,
   56.9,
   58.9,
   57.5,
   54.3,
   54.3,

In [17]:
first_weather = data[0]['daily']

In [18]:
first_weather

{'time': ['2010-01-03',
  '2010-01-04',
  '2010-01-05',
  '2010-01-06',
  '2010-01-07',
  '2010-01-08',
  '2010-01-09',
  '2010-01-10',
  '2010-01-11',
  '2010-01-12',
  '2010-01-13',
  '2010-01-14',
  '2010-01-15',
  '2010-01-16',
  '2010-01-17',
  '2010-01-18',
  '2010-01-19',
  '2010-01-20',
  '2010-01-21',
  '2010-01-22',
  '2010-01-23',
  '2010-01-24',
  '2010-01-25',
  '2010-01-26',
  '2010-01-27',
  '2010-01-28',
  '2010-01-29',
  '2010-01-30',
  '2010-01-31',
  '2010-02-01',
  '2010-02-02',
  '2010-02-03',
  '2010-02-04',
  '2010-02-05',
  '2010-02-06',
  '2010-02-07',
  '2010-02-08',
  '2010-02-09',
  '2010-02-10',
  '2010-02-11',
  '2010-02-12',
  '2010-02-13',
  '2010-02-14',
  '2010-02-15',
  '2010-02-16',
  '2010-02-17',
  '2010-02-18',
  '2010-02-19',
  '2010-02-20',
  '2010-02-21',
  '2010-02-22',
  '2010-02-23',
  '2010-02-24',
  '2010-02-25',
  '2010-02-26',
  '2010-02-27',
  '2010-02-28',
  '2010-03-01',
  '2010-03-02',
  '2010-03-03',
  '2010-03-04',
  '2010-03-05',
  '2010-03-06',
  '2010-03-07',
  '2010-03-08',
  '2010-03-09',
  '2010-03-10',
  '2010-03-11',
  '2010-03-12',
  '2010-03-13',
  '2010-03-14',
  '2010-03-15',
  '2010-03-16',
  '2010-03-17',
  '2010-03-18',
  '2010-03-19',
  '2010-03-20',
  '2010-03-21',
  '2010-03-22',
  '2010-03-23',
  '2010-03-24',
  '2010-03-25',
  '2010-03-26',
  '2010-03-27',
  '2010-03-28',
  '2010-03-29',
  '2010-03-30',
  '2010-03-31',
  '2010-04-01',
  '2010-04-02',
  '2010-04-03',
  '2010-04-04',
  '2010-04-05',
  '2010-04-06',
  '2010-04-07',
  '2010-04-08',
  '2010-04-09',
  '2010-04-10',
  '2010-04-11',
  '2010-04-12',
  '2010-04-13',
  '2010-04-14',
  '2010-04-15',
  '2010-04-16',
  '2010-04-17',
  '2010-04-18',
  '2010-04-19',
  '2010-04-20',
  '2010-04-21',
  '2010-04-22',
  '2010-04-23',
  '2010-04-24',
  '2010-04-25',
  '2010-04-26',
  '2010-04-27',
  '2010-04-28',
  '2010-04-29',
  '2010-04-30',
  '2010-05-01',
  '2010-05-02',
  '2010-05-03',
  '2010-05-04',
  '2010-05-05',
  '2010-05-06',
  '2010-05-07',
  '2010-05-08',
  '2010-05-09',
  '2010-05-10',
  '2010-05-11',
  '2010-05-12',
  '2010-05-13',
  '2010-05-14',
  '2010-05-15',
  '2010-05-16',
  '2010-05-17',
  '2010-05-18',
  '2010-05-19',
  '2010-05-20',
  '2010-05-21',
  '2010-05-22',
  '2010-05-23',
  '2010-05-24',
  '2010-05-25',
  '2010-05-26',
  '2010-05-27',
  '2010-05-28',
  '2010-05-29',
  '2010-05-30',
  '2010-05-31',
  '2010-06-01',
  '2010-06-02',
  '2010-06-03',
  '2010-06-04',
  '2010-06-05',
  '2010-06-06',
  '2010-06-07',
  '2010-06-08',
  '2010-06-09',
  '2010-06-10',
  '2010-06-11',
  '2010-06-12',
  '2010-06-13',
  '2010-06-14',
  '2010-06-15',
  '2010-06-16',
  '2010-06-17',
  '2010-06-18',
  '2010-06-19',
  '2010-06-20',
  '2010-06-21',
  '2010-06-22',
  '2010-06-23',
  '2010-06-24',
  '2010-06-25',
  '2010-06-26',
  '2010-06-27',
  '2010-06-28',
  '2010-06-29',
  '2010-06-30',
  '2010-07-01',
  '2010-07-02',
  '2010-07-03',
  '2010-07-04',
  '2010-07-05',
  '2010-07-06',
  '2010-07-07',
  '2010-07-08',
  '2010-07-09',
  '2010-07-10',
  '2010-07-11',
  '2010-07-12',
  '2010-07-13',
  '2010-07-14',
  '2010-07-15',
  '2010-07-16',
  '2010-07-17',
  '2010-07-18',
  '2010-07-19',
  '2010-07-20',
  '2010-07-21',
  '2010-07-22',
  '2010-07-23',
  '2010-07-24',
  '2010-07-25',
  '2010-07-26',
  '2010-07-27',
  '2010-07-28',
  '2010-07-29',
  '2010-07-30',
  '2010-07-31',
  '2010-08-01',
  '2010-08-02',
  '2010-08-03',
  '2010-08-04',
  '2010-08-05',
  '2010-08-06',
  '2010-08-07',
  '2010-08-08',
  '2010-08-09',
  '2010-08-10',
  '2010-08-11',
  '2010-08-12',
  '2010-08-13',
  '2010-08-14',
  '2010-08-15',
  '2010-08-16',
  '2010-08-17',
  '2010-08-18',
  '2010-08-19',
  '2010-08-20',
  '2010-08-21',
  '2010-08-22',
  '2010-08-23',
  '2010-08-24',
  '2010-08-25',
  '2010-08-26',
  '2010-08-27',
  '2010-08-28',
  '2010-08-29',
  '2010-08-30',
  '2010-08-31',
  '2010-09-01',
  '2010-09-02',
  '2010-09-03',
  '2010-09-04',
  '2010-09-05',
  '2010-09-06',
  '2010-09-07',
  '2010-09-08',
  '2010-09-09',
  '2010-09-10',
  '2010-09-11',
  '2010-09-12',
  '2010-09-13',
  '2010-09-14',
  '2010-09-15',
  '2010-09-16',
  '2010-09-17',
  '2010-09-18',
  '2010-09-19',
  '2010-09-20',
  '2010-09-21',
  '2010-09-22',
  '2010-09-23',
  '2010-09-24',
  '2010-09-25',
  '2010-09-26',
  '2010-09-27',
  '2010-09-28',
  '2010-09-29',
  '2010-09-30',
  '2010-10-01',
  '2010-10-02',
  '2010-10-03',
  '2010-10-04',
  '2010-10-05',
  '2010-10-06',
  '2010-10-07',
  '2010-10-08',
  '2010-10-09',
  '2010-10-10',
  '2010-10-11',
  '2010-10-12',
  '2010-10-13',
  '2010-10-14',
  '2010-10-15',
  '2010-10-16',
  '2010-10-17',
  '2010-10-18',
  '2010-10-19',
  '2010-10-20',
  '2010-10-21',
  '2010-10-22',
  '2010-10-23',
  '2010-10-24',
  '2010-10-25',
  '2010-10-26',
  '2010-10-27',
  '2010-10-28',
  '2010-10-29',
  '2010-10-30',
  '2010-10-31',
  '2010-11-01',
  '2010-11-02',
  '2010-11-03',
  '2010-11-04',
  '2010-11-05',
  '2010-11-06',
  '2010-11-07',
  '2010-11-08',
  '2010-11-09',
  '2010-11-10',
  '2010-11-11',
  '2010-11-12',
  '2010-11-13',
  '2010-11-14',
  '2010-11-15',
  '2010-11-16',
  '2010-11-17',
  '2010-11-18',
  '2010-11-19',
  '2010-11-20',
  '2010-11-21',
  '2010-11-22',
  '2010-11-23',
  '2010-11-24',
  '2010-11-25',
  '2010-11-26',
  '2010-11-27',
  '2010-11-28',
  '2010-11-29',
  '2010-11-30',
  '2010-12-01',
  '2010-12-02',
  '2010-12-03',
  '2010-12-04',
  '2010-12-05',
  '2010-12-06',
  '2010-12-07',
  '2010-12-08',
  '2010-12-09',
  '2010-12-10',
  '2010-12-11',
  '2010-12-12',
  '2010-12-13',
  '2010-12-14',
  '2010-12-15',
  '2010-12-16',
  '2010-12-17',
  '2010-12-18',
  '2010-12-19',
  '2010-12-20',
  '2010-12-21',
  '2010-12-22',
  '2010-12-23',
  '2010-12-24',
  '2010-12-25',
  '2010-12-26',
  '2010-12-27',
  '2010-12-28',
  '2010-12-29',
  '2010-12-30',
  '2010-12-31',
  '2011-01-01',
  '2011-01-02',
  '2011-01-03',
  '2011-01-04',
  '2011-01-05',
  '2011-01-06',
  '2011-01-07',
  '2011-01-08',
  '2011-01-09',
  '2011-01-10',
  '2011-01-11',
  '2011-01-12',
  '2011-01-13',
  '2011-01-14',
  '2011-01-15',
  '2011-01-16',
  '2011-01-17',
  '2011-01-18',
  '2011-01-19',
  '2011-01-20',
  '2011-01-21',
  '2011-01-22',
  '2011-01-23',
  '2011-01-24',
  '2011-01-25',
  '2011-01-26',
  '2011-01-27',
  '2011-01-28',
  '2011-01-29',
  '2011-01-30',
  '2011-01-31',
  '2011-02-01',
  '2011-02-02',
  '2011-02-03',
  '2011-02-04',
  '2011-02-05',
  '2011-02-06',
  '2011-02-07',
  '2011-02-08',
  '2011-02-09',
  '2011-02-10',
  '2011-02-11',
  '2011-02-12',
  '2011-02-13',
  '2011-02-14',
  '2011-02-15',
  '2011-02-16',
  '2011-02-17',
  '2011-02-18',
  '2011-02-19',
  '2011-02-20',
  '2011-02-21',
  '2011-02-22',
  '2011-02-23',
  '2011-02-24',
  '2011-02-25',
  '2011-02-26',
  '2011-02-27',
  '2011-02-28',
  '2011-03-01',
  '2011-03-02',
  '2011-03-03',
  '2011-03-04',
  '2011-03-05',
  '2011-03-06',
  '2011-03-07',
  '2011-03-08',
  '2011-03-09',
  '2011-03-10',
  '2011-03-11',
  '2011-03-12',
  '2011-03-13',
  '2011-03-14',
  '2011-03-15',
  '2011-03-16',
  '2011-03-17',
  '2011-03-18',
  '2011-03-19',
  '2011-03-20',
  '2011-03-21',
  '2011-03-22',
  '2011-03-23',
  '2011-03-24',
  '2011-03-25',
  '2011-03-26',
  '2011-03-27',
  '2011-03-28',
  '2011-03-29',
  '2011-03-30',
  '2011-03-31',
  '2011-04-01',
  '2011-04-02',
  '2011-04-03',
  '2011-04-04',
  '2011-04-05',
  '2011-04-06',
  '2011-04-07',
  '2011-04-08',
  '2011-04-09',
  '2011-04-10',
  '2011-04-11',
  '2011-04-12',
  '2011-04-13',
  '2011-04-14',
  '2011-04-15',
  '2011-04-16',
  '2011-04-17',
  '2011-04-18',
  '2011-04-19',
  '2011-04-20',
  '2011-04-21',
  '2011-04-22',
  '2011-04-23',
  '2011-04-24',
  '2011-04-25',
  '2011-04-26',
  '2011-04-27',
  '2011-04-28',
  '2011-04-29',
  '2011-04-30',
  '2011-05-01',
  '2011-05-02',
  '2011-05-03',
  '2011-05-04',
  '2011-05-05',
  '2011-05-06',
  '2011-05-07',
  '2011-05-08',
  '2011-05-09',
  '2011-05-10',
  '2011-05-11',
  '2011-05-12',
  '2011-05-13',
  '2011-05-14',
  '2011-05-15',
  '2011-05-16',
  '2011-05-17',
  '2011-05-18',
  '2011-05-19',
  '2011-05-20',
  '2011-05-21',
  '2011-05-22',
  '2011-05-23',
  '2011-05-24',
  '2011-05-25',
  '2011-05-26',
  '2011-05-27',
  '2011-05-28',
  '2011-05-29',
  '2011-05-30',
  '2011-05-31',
  '2011-06-01',
  '2011-06-02',
  '2011-06-03',
  '2011-06-04',
  '2011-06-05',
  '2011-06-06',
  '2011-06-07',
  '2011-06-08',
  '2011-06-09',
  '2011-06-10',
  '2011-06-11',
  '2011-06-12',
  '2011-06-13',
  '2011-06-14',
  '2011-06-15',
  '2011-06-16',
  '2011-06-17',
  '2011-06-18',
  '2011-06-19',
  '2011-06-20',
  '2011-06-21',
  '2011-06-22',
  '2011-06-23',
  '2011-06-24',
  '2011-06-25',
  '2011-06-26',
  '2011-06-27',
  '2011-06-28',
  '2011-06-29',
  '2011-06-30',
  '2011-07-01',
  '2011-07-02',
  '2011-07-03',
  '2011-07-04',
  '2011-07-05',
  '2011-07-06',
  '2011-07-07',
  '2011-07-08',
  '2011-07-09',
  '2011-07-10',
  '2011-07-11',
  '2011-07-12',
  '2011-07-13',
  '2011-07-14',
  '2011-07-15',
  '2011-07-16',
  '2011-07-17',
  '2011-07-18',
  '2011-07-19',
  '2011-07-20',
  '2011-07-21',
  '2011-07-22',
  '2011-07-23',
  '2011-07-24',
  '2011-07-25',
  '2011-07-26',
  '2011-07-27',
  '2011-07-28',
  '2011-07-29',
  '2011-07-30',
  '2011-07-31',
  '2011-08-01',
  '2011-08-02',
  '2011-08-03',
  '2011-08-04',
  '2011-08-05',
  '2011-08-06',
  '2011-08-07',
  '2011-08-08',
  '2011-08-09',
  '2011-08-10',
  '2011-08-11',
  '2011-08-12',
  '2011-08-13',
  '2011-08-14',
  '2011-08-15',
  '2011-08-16',
  '2011-08-17',
  '2011-08-18',
  '2011-08-19',
  '2011-08-20',
  '2011-08-21',
  '2011-08-22',
  '2011-08-23',
  '2011-08-24',
  '2011-08-25',
  '2011-08-26',
  '2011-08-27',
  '2011-08-28',
  '2011-08-29',
  '2011-08-30',
  '2011-08-31',
  '2011-09-01',
  '2011-09-02',
  '2011-09-03',
  '2011-09-04',
  '2011-09-05',
  '2011-09-06',
  '2011-09-07',
  '2011-09-08',
  '2011-09-09',
  '2011-09-10',
  '2011-09-11',
  '2011-09-12',
  '2011-09-13',
  '2011-09-14',
  '2011-09-15',
  '2011-09-16',
  '2011-09-17',
  '2011-09-18',
  '2011-09-19',
  '2011-09-20',
  '2011-09-21',
  '2011-09-22',
  '2011-09-23',
  '2011-09-24',
  '2011-09-25',
  '2011-09-26',
  '2011-09-27',
  '2011-09-28',
  '2011-09-29',
  '2011-09-30',
  '2011-10-01',
  '2011-10-02',
  '2011-10-03',
  '2011-10-04',
  '2011-10-05',
  '2011-10-06',
  '2011-10-07',
  '2011-10-08',
  '2011-10-09',
  '2011-10-10',
  '2011-10-11',
  '2011-10-12',
  '2011-10-13',
  '2011-10-14',
  '2011-10-15',
  '2011-10-16',
  '2011-10-17',
  '2011-10-18',
  '2011-10-19',
  '2011-10-20',
  '2011-10-21',
  '2011-10-22',
  '2011-10-23',
  '2011-10-24',
  '2011-10-25',
  '2011-10-26',
  '2011-10-27',
  '2011-10-28',
  '2011-10-29',
  '2011-10-30',
  '2011-10-31',
  '2011-11-01',
  '2011-11-02',
  '2011-11-03',
  '2011-11-04',
  '2011-11-05',
  '2011-11-06',
  '2011-11-07',
  '2011-11-08',
  '2011-11-09',
  '2011-11-10',
  '2011-11-11',
  '2011-11-12',
  '2011-11-13',
  '2011-11-14',
  '2011-11-15',
  '2011-11-16',
  '2011-11-17',
  '2011-11-18',
  '2011-11-19',
  '2011-11-20',
  '2011-11-21',
  '2011-11-22',
  '2011-11-23',
  '2011-11-24',
  '2011-11-25',
  '2011-11-26',
  '2011-11-27',
  '2011-11-28',
  '2011-11-29',
  '2011-11-30',
  '2011-12-01',
  '2011-12-02',
  '2011-12-03',
  '2011-12-04',
  '2011-12-05',
  '2011-12-06',
  '2011-12-07',
  '2011-12-08',
  '2011-12-09',
  '2011-12-10',
  '2011-12-11',
  '2011-12-12',
  '2011-12-13',
  '2011-12-14',
  '2011-12-15',
  '2011-12-16',
  '2011-12-17',
  '2011-12-18',
  '2011-12-19',
  '2011-12-20',
  '2011-12-21',
  '2011-12-22',
  '2011-12-23',
  '2011-12-24',
  '2011-12-25',
  '2011-12-26',
  '2011-12-27',
  '2011-12-28',
  '2011-12-29',
  '2011-12-30',
  '2011-12-31',
  '2012-01-01',
  '2012-01-02',
  '2012-01-03',
  '2012-01-04',
  '2012-01-05',
  '2012-01-06',
  '2012-01-07',
  '2012-01-08',
  '2012-01-09',
  '2012-01-10',
  '2012-01-11',
  '2012-01-12',
  '2012-01-13',
  '2012-01-14',
  '2012-01-15',
  '2012-01-16',
  '2012-01-17',
  '2012-01-18',
  '2012-01-19',
  '2012-01-20',
  '2012-01-21',
  '2012-01-22',
  '2012-01-23',
  '2012-01-24',
  '2012-01-25',
  '2012-01-26',
  '2012-01-27',
  '2012-01-28',
  '2012-01-29',
  '2012-01-30',
  '2012-01-31',
  '2012-02-01',
  '2012-02-02',
  '2012-02-03',
  '2012-02-04',
  '2012-02-05',
  '2012-02-06',
  '2012-02-07',
  '2012-02-08',
  '2012-02-09',
  '2012-02-10',
  '2012-02-11',
  '2012-02-12',
  '2012-02-13',
  '2012-02-14',
  '2012-02-15',
  '2012-02-16',
  '2012-02-17',
  '2012-02-18',
  '2012-02-19',
  '2012-02-20',
  '2012-02-21',
  '2012-02-22',
  '2012-02-23',
  '2012-02-24',
  '2012-02-25',
  '2012-02-26',
  '2012-02-27',
  '2012-02-28',
  '2012-02-29',
  '2012-03-01',
  '2012-03-02',
  '2012-03-03',
  '2012-03-04',
  '2012-03-05',
  '2012-03-06',
  '2012-03-07',
  '2012-03-08',
  '2012-03-09',
  '2012-03-10',
  '2012-03-11',
  '2012-03-12',
  '2012-03-13',
  '2012-03-14',
  '2012-03-15',
  '2012-03-16',
  '2012-03-17',
  '2012-03-18',
  '2012-03-19',
  '2012-03-20',
  '2012-03-21',
  '2012-03-22',
  '2012-03-23',
  '2012-03-24',
  '2012-03-25',
  '2012-03-26',
  '2012-03-27',
  '2012-03-28',
  '2012-03-29',
  '2012-03-30',
  '2012-03-31',
  '2012-04-01',
  '2012-04-02',
  '2012-04-03',
  '2012-04-04',
  '2012-04-05',
  '2012-04-06',
  '2012-04-07',
  '2012-04-08',
  '2012-04-09',
  '2012-04-10',
  '2012-04-11',
  '2012-04-12',
  '2012-04-13',
  '2012-04-14',
  '2012-04-15',
  '2012-04-16',
  '2012-04-17',
  '2012-04-18',
  '2012-04-19',
  '2012-04-20',
  '2012-04-21',
  '2012-04-22',
  '2012-04-23',
  '2012-04-24',
  '2012-04-25',
  '2012-04-26',
  '2012-04-27',
  '2012-04-28',
  '2012-04-29',
  '2012-04-30',
  '2012-05-01',
  '2012-05-02',
  '2012-05-03',
  '2012-05-04',
  '2012-05-05',
  '2012-05-06',
  '2012-05-07',
  '2012-05-08',
  '2012-05-09',
  '2012-05-10',
  '2012-05-11',
  '2012-05-12',
  '2012-05-13',
  '2012-05-14',
  '2012-05-15',
  '2012-05-16',
  '2012-05-17',
  '2012-05-18',
  '2012-05-19',
  '2012-05-20',
  '2012-05-21',
  '2012-05-22',
  '2012-05-23',
  '2012-05-24',
  '2012-05-25',
  '2012-05-26',
  '2012-05-27',
  '2012-05-28',
  '2012-05-29',
  '2012-05-30',
  '2012-05-31',
  '2012-06-01',
  '2012-06-02',
  '2012-06-03',
  '2012-06-04',
  '2012-06-05',
  '2012-06-06',
  '2012-06-07',
  '2012-06-08',
  '2012-06-09',
  '2012-06-10',
  '2012-06-11',
  '2012-06-12',
  '2012-06-13',
  '2012-06-14',
  '2012-06-15',
  '2012-06-16',
  '2012-06-17',
  '2012-06-18',
  '2012-06-19',
  '2012-06-20',
  '2012-06-21',
  '2012-06-22',
  '2012-06-23',
  '2012-06-24',
  '2012-06-25',
  '2012-06-26',
  '2012-06-27',
  '2012-06-28',
  '2012-06-29',
  '2012-06-30',
  '2012-07-01',
  '2012-07-02',
  '2012-07-03',
  '2012-07-04',
  '2012-07-05',
  '2012-07-06',
  '2012-07-07',
  '2012-07-08',
  '2012-07-09',
  '2012-07-10',
  '2012-07-11',
  '2012-07-12',
  '2012-07-13',
  '2012-07-14',
  '2012-07-15',
  '2012-07-16',
  '2012-07-17',
  '2012-07-18',
  '2012-07-19',
  '2012-07-20',
  '2012-07-21',
  '2012-07-22',
  '2012-07-23',
  '2012-07-24',
  '2012-07-25',
  '2012-07-26',
  '2012-07-27',
  '2012-07-28',
  '2012-07-29',
  '2012-07-30',
  '2012-07-31',
  '2012-08-01',
  '2012-08-02',
  '2012-08-03',
  '2012-08-04',
  '2012-08-05',
  '2012-08-06',
  '2012-08-07',
  '2012-08-08',
  '2012-08-09',
  '2012-08-10',
  '2012-08-11',
  '2012-08-12',
  '2012-08-13',
  '2012-08-14',
  '2012-08-15',
  '2012-08-16',
  '2012-08-17',
  '2012-08-18',
  '2012-08-19',
  '2012-08-20',
  '2012-08-21',
  '2012-08-22',
  '2012-08-23',
  '2012-08-24',
  '2012-08-25',
  '2012-08-26',
  '2012-08-27',
  '2012-08-28',
  '2012-08-29',
  '2012-08-30',
  '2012-08-31',
  '2012-09-01',
  '2012-09-02',
  '2012-09-03',
  '2012-09-04',
  '2012-09-05',
  '2012-09-06',
  '2012-09-07',
  '2012-09-08',
  '2012-09-09',
  '2012-09-10',
  '2012-09-11',
  '2012-09-12',
  '2012-09-13',
  '2012-09-14',
  '2012-09-15',
  '2012-09-16',
  '2012-09-17',
  '2012-09-18',
  '2012-09-19',
  '2012-09-20',
  '2012-09-21',
  '2012-09-22',
  '2012-09-23',
  '2012-09-24',
  '2012-09-25',
  '2012-09-26',
  '2012-09-27',
  '2012-09-28',
  ...],
 'temperature_2m_min': [45.6,
  46.4,
  43.8,
  47.5,
  42.5,
  48.3,
  47.4,
  47.9,
  47.4,
  46.5,
  47.7,
  43.2,
  43.5,
  46.3,
  45.4,
  43.1,
  43.3,
  43.7,
  45.1,
  38.7,
  35.3,
  37.1,
  38.1,
  40.7,
  43.9,
  42.3,
  42.9,
  43.5,
  42.0,
  42.8,
  45.6,
  42.3,
  49.0,
  49.2,
  46.9,
  36.6,
  40.2,
  40.0,
  34.8,
  40.6,
  41.7,
  42.1,
  46.2,
  47.1,
  49.2,
  49.7,
  49.8,
  50.1,
  46.5,
  46.6,
  43.3,
  38.3,
  43.6,
  43.5,
  47.3,
  44.6,
  40.3,
  44.0,
  50.3,
  48.7,
  43.1,
  40.9,
  46.5,
  41.4,
  44.2,
  41.1,
  37.4,
  38.0,
  40.2,
  44.5,
  40.6,
  42.4,
  48.0,
  50.6,
  49.5,
  46.7,
  45.9,
  48.1,
  46.3,
  47.8,
  46.4,
  48.6,
  43.9,
  46.5,
  48.1,
  48.7,
  50.5,
  46.7,
  45.1,
  41.8,
  42.8,
  44.2,
  48.0,
  40.1,
  45.6,
  49.1,
  49.4,
  49.7,
  47.8,
  47.4,
  41.8,
  43.9,
  44.5,
  47.2,
  47.0,
  49.4,
  49.2,
  48.0,
  44.1,
  42.1,
  41.5,
  44.8,
  46.5,
  51.0,
  51.1,
  51.5,
  46.3,
  44.3,
  46.6,
  49.2,
  50.1,
  52.9,
  53.4,
  53.1,
  51.2,
  53.8,
  51.7,
  47.9,
  46.0,
  46.2,
  53.7,
  52.5,
  52.8,
  55.5,
  51.6,
  52.7,
  51.0,
  53.6,
  55.0,
  53.6,
  49.0,
  50.5,
  47.7,
  51.6,
  55.5,
  49.0,
  50.1,
  54.6,
  57.4,
  53.4,
  52.7,
  56.1,
  58.6,
  62.2,
  59.9,
  58.5,
  56.9,
  55.9,
  56.3,
  55.4,
  56.1,
  54.8,
  57.2,
  59.8,
  54.5,
  54.6,
  55.0,
  53.2,
  54.1,
  53.7,
  52.9,
  57.3,
  57.6,
  58.2,
  57.1,
  57.5,
  59.0,
  56.9,
  57.6,
  59.3,
  59.2,
  56.5,
  55.6,
  56.6,
  55.0,
  55.5,
  55.7,
  57.6,
  62.1,
  60.3,
  60.0,
  62.0,
  66.3,
  70.6,
  72.7,
  71.0,
  68.5,
  65.3,
  62.6,
  60.0,
  58.8,
  60.9,
  63.3,
  61.4,
  58.6,
  56.9,
  56.9,
  59.5,
  59.4,
  59.8,
  59.1,
  63.2,
  66.8,
  62.5,
  59.2,
  58.2,
  57.8,
  56.1,
  55.5,
  57.1,
  55.7,
  56.8,
  59.8,
  59.5,
  62.0,
  63.0,
  68.1,
  71.1,
  70.2,
  65.4,
  67.5,
  69.2,
  62.5,
  67.3,
  74.4,
  75.3,
  66.2,
  59.0,
  56.0,
  55.2,
  56.2,
  59.1,
  60.8,
  65.4,
  67.9,
  65.4,
  60.8,
  58.1,
  57.8,
  55.9,
  53.2,
  56.3,
  59.4,
  63.3,
  62.2,
  61.2,
  56.4,
  56.4,
  57.7,
  59.4,
  59.3,
  56.4,
  55.9,
  53.3,
  57.2,
  60.9,
  62.6,
  70.6,
  69.9,
  66.3,
  66.9,
  66.3,
  66.3,
  64.0,
  60.3,
  54.7,
  55.4,
  49.8,
  50.6,
  54.0,
  60.0,
  59.4,
  62.2,
  59.7,
  60.4,
  57.8,
  57.6,
  56.5,
  57.4,
  56.9,
  58.9,
  57.5,
  54.3,
  54.3,
  54.1,
  54.4,
  49.2,
  50.4,
  49.5,
  50.8,
  51.3,
  52.8,
  49.5,
  55.4,
  59.1,
  61.2,
  58.7,
  57.1,
  52.8,
  52.0,
  44.7,
  44.7,
  46.1,
  45.2,
  48.9,
  50.5,
  49.9,
  49.4,
  46.4,
  47.6,
  51.6,
  49.3,
  44.9,
  39.7,
  41.2,
  42.9,
  36.6,
  35.8,
  35.7,
  36.9,
  35.7,
  35.7,
  37.9,
  42.0,
  45.3,
  44.7,
  45.5,
  44.5,
  42.9,
  44.5,
  44.8,
  48.0,
  48.6,
  51.5,
  50.1,
  48.2,
  46.7,
  48.5,
  48.0,
  53.2,
  54.0,
  52.9,
  50.1,
  47.9,
  45.1,
  42.8,
  44.0,
  41.6,
  41.2,
  42.1,
  44.7,
  35.3,
  32.7,
  34.8,
  39.7,
  38.2,
  37.5,
  37.5,
  41.5,
  40.2,
  45.2,
  42.9,
  38.9,
  41.5,
  41.5,
  41.8,
  46.3,
  48.3,
  49.3,
  52.5,
  52.7,
  49.2,
  47.0,
  43.1,
  43.0,
  45.4,
  42.8,
  45.5,
  45.0,
  43.9,
  43.7,
  43.0,
  44.6,
  38.8,
  40.1,
  37.2,
  34.4,
  36.6,
  42.0,
  45.6,
  46.4,
  47.2,
  40.4,
  39.3,
  40.1,
  43.8,
  42.8,
  43.3,
  49.5,
  46.4,
  37.5,
  42.5,
  42.5,
  33.9,
  38.5,
  39.4,
  38.1,
  39.8,
  41.4,
  36.4,
  30.7,
  33.4,
  36.9,
  40.5,
  49.3,
  43.8,
  45.9,
  48.2,
  49.4,
  43.3,
  46.0,
  46.8,
  47.6,
  46.9,
  44.8,
  47.8,
  49.2,
  53.3,
  49.9,
  42.6,
  48.8,
  48.1,
  41.9,
  41.0,
  39.8,
  37.3,
  46.4,
  44.5,
  48.3,
  44.1,
  44.8,
  50.0,
  54.6,
  55.6,
  54.6,
  51.8,
  47.5,
  50.0,
  50.9,
  45.4,
  40.9,
  36.4,
  40.6,
  46.0,
  46.7,
  50.1,
  43.0,
  50.1,
  54.7,
  54.4,
  54.6,
  52.1,
  53.5,
  50.4,
  48.7,
  50.4,
  50.5,
  47.8,
  50.3,
  51.2,
  55.2,
  51.8,
  51.9,
  48.6,
  51.0,
  54.6,
  56.4,
  56.2,
  56.4,
  50.8,
  52.4,
  47.8,
  45.1,
  48.2,
  51.0,

In [21]:
first_weather_df = pd.DataFrame(first_weather)

In [22]:
first_weather_df

            time  temperature_2m_min  temperature_2m_max
0     2010-01-03                45.6                75.8
1     2010-01-04                46.4                74.2
2     2010-01-05                43.8                74.6
3     2010-01-06                47.5                74.5
4     2010-01-07                42.5                74.4
...          ...                 ...                 ...
6117  2026-10-03                 NaN                 NaN
6118  2026-10-04                 NaN                 NaN
6119  2026-10-05                 NaN                 NaN
6120  2026-10-06                 NaN                 NaN
6121  2026-10-07                 NaN                 NaN

[6122 rows x 3 columns]

In [24]:
first_weather_df.tail(15)

            time  temperature_2m_min  temperature_2m_max
6107  2026-09-23                61.3                90.8
6108  2026-09-24                65.7                86.8
6109  2026-09-25                65.1                87.9
6110  2026-09-26                65.4                92.0
6111  2026-09-27                69.1                88.8
6112  2026-09-28                62.9                83.5
6113  2026-09-29                59.7                92.2
6114  2026-09-30                61.8                87.0
6115  2026-10-01                 NaN                 NaN
6116  2026-10-02                 NaN                 NaN
6117  2026-10-03                 NaN                 NaN
6118  2026-10-04                 NaN                 NaN
6119  2026-10-05                 NaN                 NaN
6120  2026-10-06                 NaN                 NaN
6121  2026-10-07                 NaN                 NaN

In [26]:
first_weather_df.isna().sum()

time                  0
temperature_2m_min    7
temperature_2m_max    7
dtype: int64

In [ ]:
weather_df = pd.DataFrame(resp.json())
weather_df.shape